### ISSUE TITLE
how to get the V28 client?

### ISSUE THREAD

**Issue by ooocici** [Hucaru/Valhalla#1]
can you tell me the V28 client download url? pls...

**Comment by zy5203344** [comment]
i have no idea. sorry

At 2018-06-29 10:38:12, "Mr.Ertiao" <notifications@github.com> wrote:


can you tell me the V28 client download url? pls...

**Comment by Hucaru** [comment]
The v28 client is on Ragezone. The localhost can also be found there. You will need the localhost without AES encryption. If you find one with AES turned on let me know and I will add to the source.

**Comment by ooocici** [comment]
thank you for your help
