### ISSUE TITLE
[BUG] Inventory duplicate on equip

### ISSUE THREAD

**Issue by ErwinsExpertise** [Hucaru/Valhalla#25]
I have noticed when either equipping an item from the inventory will allow it to be duplicated.

Steps to recreate:
Obtain item
Equip to character
Relog

Item will then be present on avatar as well as another in the inventory. I haven't really been able to look into this much but creating an issue to log the bug. I am working on monster status/skills atm so I am not able to address this bug at this time.

**Comment by Hucaru** [comment]
The inventory system is a bit of a mess as I wrote it to have something there to work with when testing other systems. The whole thing needs a rewrite along with consideration of how & when database updates should occur.
