### ISSUE TITLE
Go get error

### ISSUE THREAD

**Issue by zees-dev** [Hucaru/Valhalla#28]
**Issue**: Getting an error when running `go get`

**Error log**:
```sh
build github.com/Hucaru/Valhalla: cannot load hash/maphash: malformed module path "hash/maphash": missing dot in first path element
```

**Go version**: `go version go1.13.8 darwin/amd64`

**How to replicate**:
- Run `go get` in clean repo
- Or run `docker-compose up --build` in clean repo

**Comment by zees-dev** [comment]
I have managed to resolve this issue by updating to the latest Go Version - `golang:1.15.2`
- Will setup a PR for this

**Comment by ErwinsExpertise** [comment]
I've noticed this as well. I've reviewed the package file and there doesn't seem to be anything wrong with the import either, but GO doesn't like it for some reason. Simple GO update resolved the issue for me as well.

**Comment by Hucaru** [comment]
I have merged the PR related to this issue
