### ISSUE TITLE
Unable to log on to the game server

### ISSUE THREAD

**Issue by sheiun** [Hucaru/Valhalla#3]
I'm using master branch  

I just add a user in *adminers* and login to the login-server

The `Data.nx` convert by v28's Data.wz (Using Wz2Nx)  
And I just put Data.nx to the root folder

* Logs of `login-server`

```logs
2019/02/22 07:30:21 New client connection from [Address] 172.21.0.1:58328
2019/02/22 07:30:29 User 3 has logged in from [Address] 172.21.0.1:58328
2019/02/22 07:30:32 Error in reading from [Address] 172.21.0.1:58328 , closing the connection EOF
2019/02/22 07:30:53 New client connection from [Address] 172.21.0.1:58332
```

![image](https://user-images.githubusercontent.com/36428458/53226527-3c973100-36b6-11e9-8cb4-d912ec2ae9aa.png)

![image](https://user-images.githubusercontent.com/36428458/53226741-03ab8c00-36b7-11e9-9f51-5f980164040e.png)

**Comment by ErwinsExpertise** [comment]
Did you update your IP in handlers/loginHandlers.go ?

**Comment by sheiun** [comment]
@ErwinsExpertise I used the branch *master* so I update my like this

```go
const (
	protocol = "tcp"
	address  = "myip"
	port     = "8484"
)
```

**Comment by sheiun** [comment]
@ErwinsExpertise it works!!

Thank you very much!

But why do this project fill a private IP, is it risky if I use public IP?

![image](https://user-images.githubusercontent.com/36428458/53281810-b9371780-3769-11e9-8df1-71e39c91cfbc.png)

**Comment by ErwinsExpertise** [comment]
If you are connecting within a local network it's best to just use the local machine IP, however, if you are using a remote vps or something then you will need to use the public ip then.

**Comment by Hucaru** [comment]
The plan is to make this configurable (example config: https://github.com/Hucaru/Valhalla/blob/dev/rewrite-to-single-event-process-model/config.toml) but I want to get the interserver communication set up fully first.

branch `dev/rewrite...` is what I am working on when I get the time. Heads up, the scripting language for npcs will probably change to https://github.com/cosmos72/gomacro the new branch gets rid of mutexes and is much easier to follow.
