### ISSUE TITLE
Refactor database handling

### ISSUE THREAD

**Issue by ErwinsExpertise** [Hucaru/Valhalla#33]
Currently the database is handled by passing around a DB pointer. This method is not as efficient as it could be, and it would be better to have a database package to handle operations rather than multiple packages performing operations. 

All architecture proposals are welcome

**Comment by Hucaru** [comment]
Having a function such as in the package:
```
func connect(addr string, bufferSize int) chan int {
  // connection stuff

  return make(chan, string, bufferSize)
}

func Executor(query chan int) {
  q := <-Query
  // execute query
}
```

That is started during server creation like:
```
channel := db.connect(address, 512) // get the number from the toml settings files
go db.Executor(channel)
```

**Comment by Hucaru** [comment]
After looking at the sql package it has an internal pool, by default it creates a new worker per query. Therefore change to just have a maximum of idle connections to allow re-usable workers.
