### ISSUE TITLE
How do I start it?

### ISSUE THREAD

**Issue by shinnng** [Hucaru/Valhalla#59]
I get an error when starting it, and which version of the client should I use to connect to it?

--------------------
$ ./Valhalla.exe -type login -config config_login.toml

2022/12/28 16:28:55 Login Server
panic: open Data.nx: The system cannot find the file specified.

goroutine 1 [running]:
github.com/Hucaru/Valhalla/nx.LoadFile(0x1212973, 0x7)
        E:/Github/maplestory/Valhalla/nx/load.go:21 +0x2b4
main.(*loginServer).run(0xc000290000)
        E:/Github/maplestory/Valhalla/server_login.go:56 +0xb1
main.main()
        E:/Github/maplestory/Valhalla/main.go:25 +0x5f3

**Comment by Hucaru** [comment]
You have to generate the Data.nx file, this has been discussed here: https://github.com/Hucaru/Valhalla/discussions/48
