### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by zees-dev** [Hucaru/Valhalla#8]
Facing issues when building on the master branch:
```sh
go build
```

causes the following error:
```build github.com/Hucaru/Valhalla: cannot load github.com/Hucaru/Valhalla/server/field/droppool: no matching versions for query "latest"```

Caused by commit ```cf9095be4ba9cc2f1d14ff65f6bc04eb81f1ee23``` in the **server/channel_chat.go** file

**Comment by Hucaru** [comment]
The latest commit is 4f1af2510afd395e6ab0b5f4b913cfcbbb3fe9e1 (3 ahead)

Commit cf9095be4ba9cc2f1d14ff65f6bc04eb81f1ee23  is when I started working on a drop pool but forgot to commit the actual pool

**Comment by zees-dev** [comment]
You're right, didn't pull the latest code.
Thanks.
